markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 16
paginate_path: "page:num"

# presonal config
title: Steven Pan's Blog
description: testing...
feed: http://www.stevenpan.me/atom.xml
comments: disqus

author: Steven Pan

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
