source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
pygments: true

paginate: 5
paginate_path: "page:num"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
